### ISSUE TITLE
ModuleNotFoundError: No module named 'geopandas'

### ISSUE THREAD

**Issue by juhele** [kalab-oto/chmu-poloha-stanic#1]
I tried to solve this by running:

`pip install geopandas`

but still getting this error. Will see after reboot.

**Comment by kalab-oto** [comment]
This is `geopandas` missing, and should be resolved after installing it. However the script for QGIS don't use `geopandas`, so you can also try that :).

**Comment by juhele** [comment]
Thanks, the QGIS script works nice :-)
