### ISSUE TITLE
different data type in same columns

### ISSUE THREAD

**Issue by manmatej** [kalab-oto/chmu-poloha-stanic#4]
Bylo by super, pokud by jednotlivá pole, která se napříč vrstvami opakují měla shodný datový typ. Např. Elevation je někdy real někdy integer. Chápu, šetří to data, na druhou stranu se s tím pak ale blbě gisuje bez ruční editace. Jinak moc díky za skripty. Jsou extrémně užitečné!

**Comment by kalab-oto** [comment]
Díky, dopsal jsem to tam (https://github.com/kalab-oto/chmu-poloha-stanic/commit/8b8ac715bb08b75b9626d4473c4b1a5ee785132c), jsem rád, že se skript hodí :)
